CREATE DATABASE BD_TRIGGER

USE BD_TRIGGER

CREATE TABLE CAIXA
(
    NUMERO 	INT,
    DATA_CAIXA       DATE,
    SALDO_INICIAL   MONEY,
    SALDO_FINAL MONEY
)
GO

CREATE TABLE VENDAS
(
CODIGO  INT,
DATA_VENDA    DATE,
VALOR   MONEY
)
GO

CREATE TRIGGER uTR_MSG_CAIXA
    ON CAIXA
    AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    IF NOT EXISTS(SELECT * FROM INSERTED) -- VERIFICA SE N홒 EXISTE REGISTRO NO RETORNO DO SELECT
        -- DELETE
        PRINT 'OCORREU UMA REMO플O NA TABELA CAIXA';
    ELSE
    BEGIN
        IF NOT EXISTS(SELECT * FROM DELETED) -- A TABELA DELETED TA VAZIA? SE SIM
            -- INSERT
            PRINT 'OCORREU UMA INSER플O NA TABELA CAIXA';
        ELSE
            -- UPDATE
            PRINT 'OCORREU UMA ATUALIZA플O NA TABELA CAIXA';
    END
END;



INSERT INTO CAIXA 
VALUES (1,GETDATE(),100, 100)
GO

SELECT * FROM CAIXA

UPDATE CAIXA
SET SALDO_INICIAL = 150
WHERE NUMERO = 1

DELETE CAIXA
WHERE NUMERO = 1


---TRIGGER CREDITAR
CREATE TRIGGER uTR_VENDAS_CREDITAR
ON VENDAS
AFTER INSERT
AS
BEGIN
    DECLARE
@VALOR MONEY,
@DATA   DATE
SELECT 	@DATA = i.DATA_VENDA, @VALOR = i.VALOR FROM INSERTED as i
 UPDATE CAIXA 
SET SALDO_FINAL = SALDO_FINAL + @VALOR
 WHERE DATA_CAIXA = @DATA
END
GO


------ TRIGGER DEBITAR


CREATE TRIGGER uTR_VENDAS_DEBITAR
ON VENDAS
AFTER DELETE
AS
BEGIN
    DECLARE
    @VALOR  MONEY,
    @DATA   DATE
 SELECT @DATA = DATA_VENDA, @VALOR = VALOR FROM DELETED

UPDATE CAIXA 
SET SALDO_FINAL = SALDO_FINAL - @VALOR
WHERE DATA_CAIXA = @DATA
END
GO



--- TESTE


--INSERINDO TABELA CAIXA
INSERT INTO CAIXA
VALUES (1,GETDATE(),100, 100)
GO

-- VERIFICANDO TABELA CAIXA
SELECT * FROM CAIXA

--Testando trigger de Insert
INSERT INTO VENDAS
VALUES (2, GETDATE(), 50)

--Testando trigger de delete
DELETE FROM VENDAS 
WHERE CODIGO = 2


---- TRIGGER DE VALIDACAO

CREATE TRIGGER uTR_VALIDA_NUMERO
ON CAIXA
INSTEAD OF INSERT
AS
BEGIN
	IF EXISTS
		(SELECT * FROM CAIXA 
		WHERE NUMERO = (SELECT i.NUMERO FROM inserted i))
		BEGIN
			PRINT 'ERRO - O REGISTRO J� EXISTE NA SUA TABELA'
		END
	ELSE
		BEGIN 
			INSERT INTO CAIXA
			SELECT * FROM inserted
		END
END


---- TRIGGER DE VALIDACAO

CREATE TRIGGER uTR_VALIDA_NUMERO
ON CAIXA
INSTEAD OF INSERT
AS
BEGIN
	DECLARE @NUMEROCAIXA INT
	SET @NUMEROCAIXA = (SELECT i.NUMERO FROM inserted i)

	IF EXISTS -- VERIFICA SE O SELECT RETONA PELO MENOS 1 LINHA
		(
		SELECT * FROM CAIXA 
		WHERE NUMERO = @NUMEROCAIXA
		)
		BEGIN
			PRINT 'ERRO - O REGISTRO J� EXISTE NA SUA TABELA'
		END
	ELSE
		BEGIN 
			INSERT INTO CAIXA
			SELECT * FROM inserted
		END
END